Django/AlquilerDeAutos/AlquilerDeAutos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='rentacars/'), name='index'),
    path('rentacars/', include('rentacars.urls')),
]

Django/AlquilerDeAutos/rentacars/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    
    path('nosotros/', views.nosotros, name='nosotros'),
    path('registrarse/', views.registrarse, name='registrarse'),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view, name='logout'),

    path('listado_autos/', views.listado_autos, name='listado_autos'),
    path('alta_autos/', views.alta_autos, name='alta_autos'),
    path('editar_auto/<int:id>/', views.editar_auto, name='editar_auto'),
    path('eliminar_auto/<int:id>/', views.eliminar_auto, name='eliminar_auto'),
    path('permission_denied/', views.permission_denied_view, name='permission_denied'),

    path('crear_alquiler/<int:auto_id>/', views.crear_alquiler, name='crear_alquiler'),
    path('listado_alquileres/', views.listado_alquileres, name='listado_alquileres'),
    path('editar_alquiler/<int:alquiler_id>/', views.editar_alquiler, name='editar_alquiler'),
    path('eliminar_alquiler/<int:alquiler_id>/', views.eliminar_alquiler, name='eliminar_alquiler'),
    path('get_precio_diario/<int:id>/', views.get_precio_diario, name='obtener_precio_alquiler'),
]

Django/AlquilerDeAutos/rentacars/models.py
import datetime

from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User


class Auto(models.Model):
    marca = models.CharField(max_length=100, verbose_name='Marca')
    modelo = models.CharField(max_length=100, verbose_name='Modelo')
    color = models.CharField(max_length=50, verbose_name='Color')
    patente = models.CharField(max_length=10, verbose_name='Patente', unique=True)
    precio = models.IntegerField(verbose_name='Precio')
    imagen = models.CharField(verbose_name='Imagen')

    def __str__(self):

        return f"Marca={self.marca}, modelo={self.modelo}"


class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    apellido = models.CharField(max_length=100, verbose_name='Apellido')
    cuit = models.PositiveIntegerField(unique=True, verbose_name='CUIT')
    direccion = models.CharField(max_length=255, verbose_name='Dirección')
    telefono = models.CharField(max_length=15, verbose_name='Teléfono')
    # email = models.EmailField(unique=True, verbose_name='Correo Electrónico')
    # username = models.CharField(max_length=100, verbose_name='Nombre de Usuario')
    # password = models.CharField(max_length=100, verbose_name='Contraseña')

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

    # No es necesario porque no editamos el usuario!
    # def save(self, *args, **kwargs):
    #     # Actualiza los campos first_name y last_name del usuario
    #     # self.user.first_name = self.nombre
    #     # self.user.last_name = self.apellido
    #     # Si la contraseña ha cambiado, asegúrate de encriptarla
    #     # if not self.user.check_password(self.password):
    #     #     self.user.set_password(self.password)
    #     # self.user.save()
    #     super().save(*args, **kwargs)

class Alquiler(models.Model):
    auto = models.ForeignKey(Auto, on_delete=models.CASCADE, verbose_name='Auto')
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name='Usuario')

    fecha_inicio = models.DateField(verbose_name='Fecha de inicio')
    fecha_fin = models.DateField(verbose_name='Fecha de fin')
    precio_total = models.FloatField(verbose_name='Precio total', blank=True)

    def __str__(self):
        return f"Auto: {self.auto} ,Cliente: {self.usuario} , Fecha inicio: {self.fecha_inicio} ,fecha Entrega: {self.fecha_fin}, total: {self.precio_total}"


Auto.usuarios = models.ManyToManyField(Usuario, through=Alquiler, related_name='autos')
Usuario.autos = models.ManyToManyField(Auto, through=Alquiler, related_name='usuarios')

Django/AlquilerDeAutos/rentacars/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils import timezone

from .models import Alquiler, Auto
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label='Nombre de Usuario', required=True,
                               widget=forms.TextInput(attrs={'class': 'input_clase2'}), label_suffix='')
    password = forms.CharField(label='Password', required=True,
                               widget=forms.PasswordInput(attrs={'class': 'input_clase2'}), label_suffix='')


class Perdiste_ContraseñaForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)


class RegistrarseForm(forms.ModelForm):
    nombre = forms.CharField(max_length=30)
    apellido = forms.CharField(max_length=30)
    direccion = forms.CharField(max_length=100)
    cuit = forms.CharField(max_length=20)
    telefono = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'nombre', 'apellido', 'cuit', 'direccion', 'telefono']


class alta_autosForm(forms.Form):
    marca = forms.CharField(label='Marca', required=True, widget=forms.TextInput(attrs={'class': 'input_clase'}),
                            label_suffix='')
    modelo = forms.CharField(label='Modelo', required=True, widget=forms.TextInput(attrs={'class': 'input_clase'}),
                             label_suffix='')
    color = forms.CharField(label='Color', required=True, widget=forms.TextInput(attrs={'class': 'input_clase'}),
                            label_suffix='')
    patente = forms.CharField(label='Patente', required=True, widget=forms.TextInput(attrs={'class': 'input_clase'}),
                              label_suffix='')
    precio = forms.CharField(label='Precio', required=True, widget=forms.TextInput(attrs={'class': 'input_clase'}),
                             label_suffix='')
    imagen = forms.CharField(label='Imagen', required=True, widget=forms.TextInput(attrs={'class': 'input_clase'}),
                             label_suffix='')

    def clean_Marca(self):
        marca = self.cleaned_data['marca']
        if not marca.isalpha():
            raise ValidationError("La Marca solo puede estar compuesta por letras")
        return self.cleaned_data['Marca']
    
    def clean_patente(self):
        patente = self.cleaned_data['patente']
        if Auto.objects.filter(patente=patente).exists():
            raise ValidationError("Ya existe un auto con esta patente")
        return patente
    
    def clean_Precio(self):
        precio = self.cleaned_data['precio']
        # Intenta convertir el precio a un entero
        try:
            precio_entero = int(precio)
        except ValueError:
            raise ValidationError("El Precio solo puede estar compuesto por números")
        return precio_entero

    def clean(self):
        print(self.cleaned_data)
        return self.cleaned_data


class AlquilerForm(forms.ModelForm):

    class Meta:
        model = Alquiler
        fields = ['fecha_inicio', 'fecha_fin', 'precio_total']
        widgets = {
            'fecha_inicio': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
            'fecha_fin': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
        }
        labels = {
            'fecha_inicio': "Inicio de alquiler: ",
            'fecha_fin': "Fin de Alquiler: "
        }

    def __init__(self, *args, **kwargs):
        super(AlquilerForm, self).__init__(*args, **kwargs)
        self.fields['precio_total'].disabled = True,
        self.fields['fecha_inicio'].initial = timezone.now().strftime('%Y-%m-%d')
        self.fields['fecha_fin'].initial = timezone.now().strftime('%Y-%m-%d')

Django/AlquilerDeAutos/rentacars/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from .import forms 
from .forms import alta_autosForm
from .models import Auto, Usuario, Alquiler
from .forms import AlquilerForm
from .forms import RegistrarseForm
from django.contrib.auth import login, logout
from django.urls import reverse_lazy

# Otra opcion: from .forms import * (y se le quita forms abajo)

# Create your views here.

def obtener_autos():
    autos = Auto.objects.all()
    contexto = {'autos': autos}
    return contexto

def get_precio_diario(request, id):
    auto = get_object_or_404(Auto, id=id)
    data = {
        'precio_diario': str(auto.precio)
    }
    return JsonResponse(data)

def index(request):
    contexto = obtener_autos()
    # Accedo a la BBDD a traves de los modelos
    return render(request, 'rentacars/index.html', contexto)

def usuario_logout(request):
    logout(request)
    return render(request, 'login')

@login_required
@user_passes_test(lambda u: u.is_staff,login_url=reverse_lazy('permission_denied'))
def listado_autos(request):
    contexto = obtener_autos()
    return render(request, 'rentacars/listado_autos.html', contexto)

@login_required
@user_passes_test(lambda u: u.is_staff,login_url=reverse_lazy('permission_denied'))
def editar_auto(request, id):
    auto = get_object_or_404(Auto, id=id)
    if request.method == 'POST':
        auto.marca = request.POST['marca']
        auto.modelo = request.POST['modelo']
        auto.color = request.POST['color']
        auto.precio = request.POST['precio']
        auto.imagen = request.POST['imagen']
        auto.save()
        messages.success(request, 'Auto actualizado con éxito.')
        return redirect('listado_autos')
    return render(request, 'rentacars/listado_autos.html')

@login_required
@user_passes_test(lambda u: u.is_staff,login_url=reverse_lazy('permission_denied'))
def eliminar_auto(request, id):
    auto = get_object_or_404(Auto, id=id)
    if request.method == 'POST':
        auto.delete()
        messages.success(request, 'Auto eliminado con éxito.')
        return redirect('listado_autos')
    return render(request, 'rentacars/listado_autos.html')

@login_required
@user_passes_test(lambda u: u.is_staff,login_url=reverse_lazy('permission_denied'))
def alta_autos(request):
    contexto = {}
    if request.method == "GET":
        contexto['alta_autos_form'] = alta_autosForm()
    else:
        form = alta_autosForm(request.POST)
        contexto['alta_autos_form'] = form  
        # Validar el formulario
        if form.is_valid():
            messages.success(request, 'El Auto fue dado de alta con éxito')
            nuevo_auto = Auto(
                marca=form.cleaned_data['marca'],
                modelo=form.cleaned_data['modelo'],
                color=form.cleaned_data['color'],
                patente=form.cleaned_data['patente'],
                precio=form.cleaned_data['precio'],
                imagen=form.cleaned_data['imagen'])
            nuevo_auto.save()

            return redirect('alta_autos')

    return render(request, 'rentacars/alta_autos.html', contexto)



def registrarse(request):
    contexto = {}
    if request.method == "GET":
        contexto['Registrarse_Form'] = RegistrarseForm()
    else:
        form = RegistrarseForm(request.POST)
        contexto['Registrarse_Form'] = form
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                email=form.cleaned_data['email'],
                first_name=form.cleaned_data['nombre'],  
                last_name=form.cleaned_data['apellido'] 
            )
            nuevo_usuario = Usuario(
                user=user,
                nombre=form.cleaned_data['nombre'],
                apellido=form.cleaned_data['apellido'],
                cuit=form.cleaned_data['cuit'],
                direccion=form.cleaned_data['direccion'],
                telefono=form.cleaned_data['telefono'],
                # username=form.cleaned_data['username'],
                # password=form.cleaned_data['password'],
                # email=form.cleaned_data['email'],
            )
            nuevo_usuario.save()
            login(request, user)  # Iniciar sesión automáticamente
            return redirect('index')
    return render(request, 'rentacars/registrarse.html', contexto)

@login_required()
def crear_alquiler(request, auto_id):
    auto = get_object_or_404(Auto, id=auto_id)

    if request.method == 'POST':
        form = AlquilerForm(request.POST)
        if form.is_valid():
            dias = form.cleaned_data['fecha_fin'] - form.cleaned_data['fecha_inicio']
            alquiler = form.save(commit=False)
            usuario_auth = request.user
            try:
                usuario = Usuario.objects.get(user=usuario_auth)
                alquiler.usuario = usuario
                alquiler.auto = auto
                alquiler.precio_total = auto.precio * (dias.days + 1)
                alquiler.save()
                messages.success(request, 'Alquiler creado con éxito.')
                return redirect('listado_alquileres')
            except Usuario.DoesNotExist:
                messages.error(request, 'Usuario no encontrado.')
        else:
            messages.error(request, 'Formulario no válido. Por favor, verifica los datos ingresados.')
    else:
        form = AlquilerForm()

    return render(request, 'rentacars/crear_alquiler.html', {'form': form, 'auto': auto})

@login_required
def listado_alquileres(request):
    usuario_auth = request.user  # Esto es una instancia del modelo User
    try:
        if usuario_auth.is_superuser:
            alquileres = Alquiler.objects.all()
        else:
            usuario = Usuario.objects.get(user=usuario_auth)
            alquileres = Alquiler.objects.filter(usuario=usuario)
        context = {'alquileres': alquileres}
        return render(request, 'rentacars/listado_alquileres.html', context)
    except Usuario.DoesNotExist:
        messages.error(request, 'Usuario no encontrado.')
        return redirect('index')


@login_required
def editar_alquiler(request, alquiler_id):
    alquiler = get_object_or_404(Alquiler, id=alquiler_id)
    auto = get_object_or_404(Auto, id=alquiler.auto_id)

    if request.method == 'POST':
        form = AlquilerForm(request.POST, instance=alquiler)
        if form.is_valid():
            dias = form.cleaned_data['fecha_fin'] - form.cleaned_data['fecha_inicio']
            alquiler = form.save(commit=False)
            usuario_auth = request.user
            try:
                usuario = Usuario.objects.get(user=usuario_auth)
                alquiler.usuario = usuario
                alquiler.auto = auto
                alquiler.precio_total = auto.precio * (dias.days + 1)
                alquiler.save()
                messages.success(request, 'Alquiler actualizado con éxito.')
                return redirect('listado_alquileres')
            except Usuario.DoesNotExist:
                messages.error(request, 'Usuario no encontrado.')

            # form.save()
            # messages.success(request, 'Alquiler actualizado con éxito.')
            # return redirect('listado_alquileres')
    else:
        form = AlquilerForm(instance=alquiler)

    return render(request, 'rentacars/editar_alquiler.html', {'form': form, 'auto': auto, 'alquiler':alquiler})

@login_required
def eliminar_alquiler(request, alquiler_id):
    alquiler = get_object_or_404(Alquiler, id=alquiler_id)

    if request.method == 'POST':
        alquiler.delete()
        messages.success(request, 'Alquiler eliminado con éxito.')
        return redirect('listado_alquileres')

    return render(request, 'rentacars/eliminar_alquiler.html', {'alquiler': alquiler})


def nosotros(request):
    return render(request, 'rentacars/nosotros.html')


@login_required
def permission_denied_view(request):
    messages.error(request, 'No tienes permisos para acceder a esta página.')
    return redirect('index')

Django/AlquilerDeAutos/rentacars/templates/rentacars/alta_autos.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <title>RentaCars - Alta Autos</title>
    <meta name="description" content="¡Alquila un coche en Buenos Aires y explora la ciudad a tu propio ritmo! Encuentra las mejores opciones de alquiler de coches 
    con nosotros.">
    <meta name="keywords" content="Alquiler de coches Buenos Aires, Rentar auto Buenos Aires">
    <meta name="Grupo5-Django" content="Grupo5-Django">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'rentacars/styles/altaAutos.css' %}">
</head>
<body>
    <div class="contenedor">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form method="POST" action="{% url 'alta_autos' %}">
            <h1>Alta de Autos</h1>
            {% csrf_token %}
            {{ alta_autos_form.as_p }}
            
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="button" ><a href="{% url 'index' %}" style="color: white; text-decoration: none;">Volver</a></button>
                <button type="submit" >Guardar</button>
            </div>
        </form>
        <img src="{% static 'rentacars/img/logo3.png' %}" alt="logo">
    </div>
</body>
</html>

Django/AlquilerDeAutos/rentacars/templates/rentacars/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <title>RentaCars - {% block titulo %}{% endblock %}</title>
    <meta name="description" content="¡Alquila un coche en Buenos Aires y explora la ciudad a tu propio ritmo! Encuentra las mejores opciones de alquiler de coches 
    con nosotros.">
    <meta name="keywords" content="Alquiler de coches Buenos Aires, Rentar auto Buenos Aires">
    <meta name="Grupo5-Django" content="Grupo5-Django">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'rentacars/styles/base.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    {% block extra_css%} {% endblock %}
</head>

<body>
    <header>
        <div class="container-fluid">
            <div class="navb-logo">
                <img src="{% static 'rentacars/img/logo1.svg'%}" alt="logo">
            </div>
            <nav class="navb-items">
                <ul>
                    <li class="item">
                        <a href="{% url 'index' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="item">
                            <a href="{% url 'listado_alquileres' %}">Listado de Alquileres</a>
                        </li>
                    {% endif %}
                    
                    <li class="item">
                        <a href="{% url 'nosotros' %}">Nosotros</a>
                    </li>

                    {% if user.is_staff %}
                        <li class="item">
                            <a href="{% url 'listado_autos'%}">Lista Autos</a>
                        </li>
                        <li class="item">
                            <a href="{% url 'alta_autos'%}">Alta Autos</a>
                        </li>
                    {% endif %}

                    <li class="item">
                        {% if not user.is_authenticated %}
                        <a class="item-button" href="{% url 'login' %}"><i class="fa-solid fa-user"></i>Login</a>
                        {% else %}
                        <a class="item-button" href="{% url 'login' %}"><i class="fa-solid fa-user"></i>{{user}}</a>
                        {% endif %}
                    </li>
                </ul>

                <!-- Button trigger modal -->
                <div class="mobile-toogler d-lg-none">
                    <a href="#" data-bs-toggle="modal" data-bs-target="#navbModal">
                        <i class="fa-solid fa-bars"></i>
                    </a>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="navbModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i
                                        class="fa-solid fa-x"></i></button>
                            </div>
                            <div class="modal-body">
                                <div class="modal-line">
                                    <i class="fa-solid fa-house"></i> <a href="{% url 'index' %}">Home</a>
                                </div>
                                 {% if user.is_authenticated %}
                                    <div class="modal-line">
                                        <i class="fa-solid fa-list"></i> <a href="{% url 'listado_alquileres' %}">Listado de Alquileres</a>
                                    </div>
                                {% endif %}
                                
                                <div class="modal-line">
                                   <i class="fa-solid fa-people-group"></i> <a href="{% url 'nosotros' %}" >Nosotros</a>
                                </div>
                                
                                {% if user.is_staff %}
                                    <div class="modal-line">
                                        <i class="fa-solid fa-list"></i> <a href="{% url 'listado_autos'%}">Lista Autos</a>
                                    </div>
                                    <div class="modal-line">
                                        <i class="fa-solid fa-plus"></i> <a href="{% url 'alta_autos'%}">Alta Autos</a>
                                    </div>
                                {% endif %}

                                {% if not user.is_authenticated %}
                                  <a class="item-button" href="{% url 'login' %}"><i class="fa-solid fa-user"></i>Login</a>
                                {% else %}
                                  <a class="item-button" href="{% url 'login' %}"><i class="fa-solid fa-user"></i>{{user}}</a>
                                {% endif %}
                                
                            </div>
                            <div class="mobil-modal-footer">
                                <a target="_blank" href="#"><i class="fa-brands fa-facebook"></i></a>
                                <a target="_blank" href="#"><i class="fa-brands fa-instagram"></i></a>
                                <a target="_blank" href="#"><i class="fa-brands fa-youtube"></i></a>
                                <a target="_blank" href="#"><i class="fa-brands fa-square-x-twitter"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>

    <main>
        <div class="container mt-4">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>

        {% block main %}{% endblock %}
    </main>


    <footer>
        <div class="footerContainer">
            <img src="{% static 'rentacars/img/logo3.png'%}" alt="">
            <div class="socialIcons">
                <a target="_blank" href="#"><i class="fa-brands fa-facebook"></i></a>
                <a target="_blank" href="#"><i class="fa-brands fa-instagram"></i></a>
                <a target="_blank" href="#"><i class="fa-brands fa-youtube"></i></a>
                <a target="_blank" href="#"><i class="fa-brands fa-square-x-twitter"></i></a>
            </div>
            <div class="footerNav">
                <ul>
                    <li class="item"><a href="{% url 'index' %}">Inicio</a></li>
                    <li class="item"><a href="{% url 'nosotros' %}">Nosotros</a></li>

                </ul>
                <div class="footercopy">
                    <p>Copyright &copy;2024 - Todos los derechos Reservados</p>
                </div>

            </div>
        </div>

    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

Django/AlquilerDeAutos/rentacars/templates/rentacars/crear_alquiler.html
{% extends "rentacars/base.html" %}
{% load static %}
{% block titulo %}Crear alquiler{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'rentacars/styles/crear_alquiler.css' %}">
{% endblock %}

{% block main %}
<div class="container mt-5">
    
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <img src="{{ auto.imagen }}" class="card-img-top" alt="{{ auto.marca }} {{ auto.modelo }}">
                <div class="card-body">
                    <h5 class="card-title">{{ auto.marca }} {{ auto.modelo }}</h5>
                    <p class="card-text"><strong>Color:</strong> {{ auto.color }}</p>
                    <p class="card-text"><strong>Precio:</strong> ${{ auto.precio }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <input type="hidden" id="id_auto" value="{{ auto.id }}">
                    <form method="post" action="{% url 'crear_alquiler' auto.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a href="{% url 'listado_autos' %}" class="btn btn-secondary">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    
<script src="{% static 'rentacars/js/alquiler_autos.js' %}"></script>
    
{% endblock %}

Django/AlquilerDeAutos/rentacars/templates/rentacars/editar_alquiler.html
{% extends "rentacars/base.html" %}
{% load static %}
{% block titulo %}Crear alquiler{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'rentacars/styles/crear_alquiler.css' %}">
{% endblock %}

{% block main %}
<div class="container mt-5">
    
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <img src="{{ auto.imagen }}" class="card-img-top" alt="{{ auto.marca }} {{ auto.modelo }}">
                <div class="card-body">
                    <h5 class="card-title">{{ auto.marca }} {{ auto.modelo }}</h5>
                    <p class="card-text"><strong>Color:</strong> {{ auto.color }}</p>
                    <p class="card-text"><strong>Precio:</strong> ${{ auto.precio }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <input type="hidden" id="id_auto" value="{{ auto.id }}">
                    <form method="post" action="{% url 'editar_alquiler' alquiler.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a href="{% url 'listado_autos' %}" class="btn btn-secondary">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    
<script src="{% static 'rentacars/js/alquiler_autos.js' %}"></script>
    
{% endblock %}

Django/AlquilerDeAutos/rentacars/templates/rentacars/footer.html
{% load static %}

<footer>
    <div class="footerContainer">
        <img src="{% static 'rentacars/img/logo3.png' %}" alt="">
        <div class="socialIcons">
            <a target="_blank" href="#"><i class="fa-brands fa-facebook"></i></a>
            <a target="_blank" href="#"><i class="fa-brands fa-instagram"></i></a>
            <a target="_blank" href="#"><i class="fa-brands fa-youtube"></i></a>
            <a target="_blank" href="#"><i class="fa-brands fa-square-x-twitter"></i></a>
        </div>
        <div class="footerNav">
            <ul>
                <li class="item"><a href="{% url 'index' %}">Inicio</a></li>
                <li class="item"><a href="{% url 'nosotros' %}">Nosotros</a></li>
                <li class="item"><a href="{% url 'contacto' %}">Contacto</a></li>
            </ul>
            <div class="footercopy">
                <p>Copyright &copy;2024 - Todos los derechos Reservados</p>
            </div>

        </div>
    </div>
</footer>